apiVersion: v1
kind: Service
metadata:
  # This exact name is what Istio and the internal DNS use for routing
  name: {{ .Values.nameOverride }}-svc 
  namespace: default
spec:
  selector:
    app: {{ .Values.nameOverride }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
