nameOverride: frontend-api

image:
  repository: localhost:5001/frontend-api
  tag: 1.2.5

env:
  CRUD_API_URL: http://crud-api-svc.default.svc.cluster.local
  FLIPT_URL: http://flipt.default.svc.cluster.local:8080
  LOG_LEVEL: debug

autoscaling:
  minReplicas: 1
  maxReplicas: 3
